---
- block:
    - name: Check python3
      command: "{{ python3_executable }} --version"
      register: python3_check
      ignore_errors: True

    - name: DEBUG python3 check result
      debug:
        var: python3_check
      when: debug | default(false)

    - set_fact:
        install_python3: "{{ python3_check.failed }}"

  when: install_python3 is undefined

- block:
    - name: Install python3 package
      package:
        name: python3
        state: present
      ignore_errors: True
      register: python3_install
      when: not install_python3_from_source

    - name: Install python3 from source
      block:
        - name: Include variables
          include_vars:
            file: "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"

        - name: Install Required packages for python3 installation
          package:
            name: "{{ item }}"
            state: present
          with_items: "{{ packages_to_install }}"

        - name: Download python3
          get_url:
            url: "{{ python_download_url }}"
            dest: "{{ python_downloaded_file }}"
          changed_when: false

        - name: Extract python3
          unarchive:
            src: "{{ python_downloaded_file }}"
            dest: "{{ python_dir | dirname }}"
            remote_src: yes

        - name: Configure python3
          command: |
            ./configure
            --prefix={{ python_path }}
            --enable-shared
            --enable-ipv6
            LDFLAGS=-Wl,-rpath={{ python_path }}/lib,--disable-new-dtags
          args:
            chdir: "{{ python_dir }}"

        - name: Compile python3
          command: make
          args:
            chdir: "{{ python_dir }}"

        - name: Install python3
          command: make install
          become: yes
          args:
            chdir: "{{ python_dir }}"

        - name: Add python to the PATH in bashrc
          blockinfile:
            path: ~/.bashrc
            block: |
              PATH=$PATH:{{ python_path }}/bin

      when: install_python3_from_source or python3_install.rc != "0"

    - name: Verify python3 version
      command: "{{ python3_executable }} --version"
      register: python3_version_result

    - name: DEBUG python3 verify result
      debug:
        var: python3_version_result
      when: debug | default(false)

  when: install_python3

- block:
    - name: Check pip3
      command: "{{ pip3_executable }} --version"
      register: pip3_check
      ignore_errors: True

    - name: DEBUG pip3 check result
      debug:
        var: pip3_check
      when: debug | default(false)

    - set_fact:
        install_pip3: "{{ pip3_check.failed }}"

  when: install_pip3 is undefined

- block:
    - name: Install pip3 package
      package:
        name: python3-pip
        state: present
      when: not install_python3_from_source

    - name:  Install pip3 from source
      block:
        - name: Download pip3
          get_url:
            url: "{{ pip_download_url }}"
            dest: "{{ ansible_user_dir }}"
          changed_when: false

        - name: Install pip3
          command: "{{ python3_executable }} get-pip.py"

      when: install_python3_from_source
  when: install_pip3

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: "{{ pip3_executable }}"