---
- name: Gathering data for Kafka post migration
  tags: kafka-post-migration
  hosts: all
  gather_facts: False
  roles:
    - { role: get_hostnames_where_role_group_is_located, role_group_filter: KAFKA_BROKER }

- name: Kafka post migration steps
  tags: kafka-post-migration
  hosts: KAFKA_BROKER
  vars:
    service_name: kafka
  gather_facts: False
  roles:
    - { role: query_configuration_from_service, service_name: kafka, configuration_name: log.dirs,
        configuration_type: ROLE, role_name_filter: "kafka-KAFKA_BROKER" }
    - { role: query_configuration_from_service, service_name: kafka, configuration_name: jmx_port,
        configuration_type: ROLE, role_name_filter: "kafka-KAFKA_BROKER" }
    - role: is_service_exists
      service_name: ranger_kms
    - role: query_configuration_from_service
      service_name: ranger_kms
      configuration_name: ranger_kms_https_port
      configuration_type: ROLE
      when: is_service_exists_result
  tasks:
    - block: # https://docs.cloudera.com/cdp-private-cloud-upgrade/latest/upgrade-hdp3/topics/amb3-kafka-cleanup.html
        - name: Check if meta.properties file exists in log.dirs
          stat:
            path: "{{ log_dirs }}/meta.properties"
          register: result
        - name: Copy meta.properties file located in log.dirs
          copy:
            src: "{{ log_dirs }}/meta.properties"
            dest: /tmp
            remote_src: yes
          when: result.stat.exists
        - name: Delete old meta.properties file
          file:
            path: "{{ log_dirs }}/meta.properties"
            state: absent
          when: result.stat.exists
      become: yes

    # https://docs.cloudera.com/cdp-private-cloud-upgrade/latest/upgrade-hdp3/topics/amb3-kafka-port.html
    - name: Change the Kafka JMX port value if the Ranger KMS port is conflicting with Kafka JMX port.
      include_role:
        name: update_configuration_in_role_configuration_group
      vars:
        role_configuration_group_name: "kafka-KAFKA_BROKER"
        configuration_name: "jmx_port"
        configuration_value: "{{ kafka_new_jmx_port }}"
      when:
        - ranger_kms_https_port is defined
        - jmx_port == ranger_kms_https_port

    - name: Setup Kafka Ranger plugin
      kafka_ranger_plugin:
        cm_configuration: "{{ cm_configuration_dictionary }}"
      delegate_to: localhost
      environment:
        - TRANSITION_LOG_DIR: "{{ transition_log_dir }}"
        - TRANSITION_TAG_LOG_FILE: "{{ ansible_run_tags | join('_') + '-tag.log'}}"
      run_once: True

    - name: Restart Service
      include_role:
        name: restart_service