---
- name: Get Ranger DB host
  hosts: localhost
  gather_facts: False
  tags: ranger-kms-post-migration
  roles:
    - { role: query_configuration_from_service, service_name: ranger, configuration_name: ranger_database_host,
        configuration_type: SERVICE}
  tasks:
    - name: Create Ranger DB host group
      add_host:
        name: "{{ ranger_database_host }}"
        groups: ranger_db_host

- name: Update keyadmin password
  hosts: ranger_db_host
  gather_facts: False
  tags: ranger-kms-post-migration
  tasks:
    - name: Get ranger variables
      loop: [ ranger_database_name, ranger_database_port, ranger_database_user, ranger_database_password, keyadmin_user_password ]
      include_role:
        name: query_configuration_from_service
      vars:
        service_name: ranger
        configuration_type: SERVICE
        configuration_name: "{{ item }}"
    - name: Make update command
      vars:
        password_token: "{{ keyadmin_user_password }}{keyadmin}"
        hashed_password_token: "{{ password_token|ansible.builtin.md5 }}"
      community.mysql.mysql_query:
        login_host: "{{ groups['ranger_db_host'][0] }}"
        login_port: "{{ ranger_database_port|int }}"
        login_db: "{{ ranger_database_name }}"
        login_user: "{{ ranger_database_user }}"
        login_password: "{{ ranger_database_password }}"
        query: "update x_portal_user set password = '{{ hashed_password_token }}' where login_id = 'keyadmin'"
