- name: Does service exists
  block:
    - name: Service to be checked
      debug:
          var: service_name
    - name: Check service via CM API
      is_service_exists:
        service_name: "{{ service_name }}"
        cm_configuration: "{{ cm_configuration_dictionary }}"
      register: is_service_exists_result_tmp
    - name: Print response
      debug:
        var: is_service_exists_result_tmp['message']
  run_once: True
  delegate_to: localhost

- set_fact:
    is_service_exists_result: "{{ is_service_exists_result_tmp['message'] | bool }}"
