- name: Collecting am2cm-solr-client info
  set_fact:
    am2cm_solr_client_config: "{{ am2cm_solr_client_config | default(am2cm_solr_client_configuration_dictionary) | combine ( {item.key : item.value}) }}"
  with_items:
    - { 'key': 'backup_dir' , 'value': "{{ service_backup_dir }}/{{ solr_collection }}"}

- name: Print am2cm-solr-client config
  debug:
    var: am2cm_solr_client_config

- name: "Create the backup directory for {{ solr_collection }}"
  file:
    path: "{{ am2cm_solr_client_config['backup_dir'] }}"
    mode: 0777
    state: directory
  become: yes

- name: "Backup the documents of {{ solr_collection }}"
  am2cm_solr_client:
    am2cm_solr_client_configuration: "{{ am2cm_solr_client_config }}"
    solr_action: 'backup'
    solr_collection: "{{ solr_collection }}"
    log_file_path: "{{ am2cm_solr_client_log_file }}"
  register: res
  become: yes

- name: Print output
  debug:
    var: res.stdout_lines

- name: Fail if am2cm_solr_client couldn't backup the collection"
  fail:
    msg:
      - "An error occurred while downloading the {{ solr_collection }} collection!"
  when: res.failed|d(false)