---
- name: Rollback Atlas
  hosts: backup_atlas[0]
  gather_facts: False
  tags: atlas-rollback
  vars:
    service_name: atlas
    atlas_tables: "{{ ['atlas_titan', 'ATLAS_ENTITY_AUDIT_EVENTS'] if am2cm_source_version == 'HDP2' else ['atlas_janus', 'ATLAS_ENTITY_AUDIT_EVENTS'] }}"
    keytab: "{{ atlas_service_keytab }}"
    principal: "{{ atlas_service_principal }}"
    become_user: "{{ atlas_user_name }}"
    skip_kinit: False
  roles:
    - prepare_to_rollback_service
  tasks:
    # https://docs.cloudera.com/cdp-private-cloud-upgrade/latest/upgrade-hdp3/topics/amb3_rollback_hdp3_atlas_7.1.7.html

    - name: "Disable HBase tables"
      shell: "echo \"disable '{{ item }}'\" | hbase shell"
      loop: "{{ atlas_tables }}"
      become: yes
      become_user: "{{ atlas_user_name }}"

    - name: "Restore snapshot from HBase tables"
      shell: "echo \"restore_snapshot '{{ item }}-backup'\" | hbase shell"
      loop: "{{ atlas_tables }}"
      become: yes
      become_user: "{{ atlas_user_name }}"

    - name: "Re-enable HBase tables"
      shell: "echo \"enable '{{ item }}'\" | hbase shell"
      loop: "{{ atlas_tables }}"
      become: yes
      become_user: "{{ atlas_user_name }}"

    - name: Start Atlas service
      include_role:
        name:
          start_hdp_service
