- name: Get Ranger-KMS hosts
  tags: ranger-kms-db-schema-upgrade
  gather_facts: False
  hosts: all
  roles:
    - {role: get_hostnames_where_role_group_is_located, role_group_filter: "RANGER_KMS_SERVER"}

- name: Distribute JDBC driver
  tags: ranger-kms-db-schema-upgrade
  gather_facts: false
  hosts: RANGER_KMS_SERVER  # so all service hosts are eligible for running the DB upgrade on
  roles:
    - distribute_jdbc_drivers

- name: Schema migration for Ranger-KMS DB
  tags: ranger-kms-db-schema-upgrade
  gather_facts: False
  hosts: RANGER_KMS_SERVER[0]
  tasks:
    - name: Query multiple Ranger-KMS configurations
      include_role:
        name: query_configuration_from_service
      vars:
        service_name: ranger_kms
        configuration_name: "{{ item }}"
        configuration_type: "SERVICE"
      loop:
        - 'ranger_kms_database_type'
        - 'ranger_kms_database_host'
        - 'ranger_kms_database_port'
        - 'ranger_kms_database_name'
        - 'ranger_kms_database_user'
        - 'ranger_kms_database_password'

    - name: Set JDBC driver path according to database type
      set_fact:
        jdbc_driver_path: "{{ jdbc_remote_driver_directory }}/\
        {{ lookup('vars', 'jdbc_driver_' + ranger_kms_database_type + '_basename') }}.jar"

    # workaround: regex_replace for postgresql is needed
    # DB_FLAVOR in the install.properties is represented as 'POSTGRES' i.e. #DB_FLAVOR=MYSQL|ORACLE|POSTGRES|MSSQL|SQLA
    - name: Create db_related_dict
      set_fact:
        db_related_dict:
          db_root_user: "{{ ranger_kms_db_root_user }}"
          db_root_password: "{{ ranger_kms_db_root_user_password }}"
          db_user: " {{ ranger_kms_database_user }}"
          db_password: "{{ ranger_kms_database_password }}"
          db_host: "{{ ranger_kms_database_host }}"
          db_port: "{{ ranger_kms_database_port }}"
          db_name: "{{ ranger_kms_database_name }}"
          DB_FLAVOR: "{{ ranger_kms_database_type | upper | regex_replace('POSTGRESQL','POSTGRES') }}"
          SQL_CONNECTOR_JAR: "{{ jdbc_driver_path }}"

    - name: Update the install.properties file with the appropriate Ranger-KMS properties
      lineinfile:
        path: "{{ ranger_kms_home }}/install.properties"
        line: "{{ item.key }}={{ item.value }}"
        regexp: "^{{ item.key }}="
      become: yes
      loop: "{{ db_related_dict | dict2items }}"

    - name: Get java home for db_script
      include_role:
        name: get_java_home_of_current_host

    - name: Create a db_script_runner_env environment dictionary
      set_fact:
        db_script_runner_env:
          RANGER_KMS_HOME: "{{ ranger_kms_home }}"
          JAVA_HOME: "{{ java_home }}"

    - name: Print all the values that are used for the DB connection (and were setup here)
      debug:
        msg: "{{ item.key }}={{ item.value }}"
      loop: "{{ db_related_dict | combine(db_script_runner_env) | dict2items }}"

    - name: Run the dba_script.py if db_user needs to be created
      shell: |
        python2.7 "{{ ranger_kms_home }}"/dba_script.py -q
      when: ranger_kms_create_db_user
      become: yes
      register: dba_script_result
      environment: "{{ db_script_runner_env }}"
      changed_when:
        - "'user ' + ranger_kms_database_user + ' already exists for host' not in dba_script_result.stderr"
        - "'Database ' + ranger_kms_database_name + ' already exists' not in dba_script_result.stderr"

    - name: Run the db_setup.py to apply the patches
      shell: |
        python2.7 "{{ ranger_kms_home }}"/db_setup.py
      become: yes
      register: db_setup_result
      environment: "{{ db_script_runner_env }}"
      changed_when: '"Table ranger_masterkey already exists in database" not in db_setup_result.stderr'