# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Upgrade Cloudera Manager Agents
  hosts: cloudera_manager, cluster
  tags: cm-upgrade
  become: yes
  any_errors_fatal: true
  roles:
    - { role: cloudera_manager/agent, state: latest }


- name: Upgrade Cloudera Manager Server
  hosts: cloudera_manager
  tags: cm-upgrade
  become: yes
  any_errors_fatal: true
  roles:
    - { role: cloudera_manager/server, state: latest }


